spring:
  application:
    name: payment
  datasource:
    username: "root"
    password: "$CDB1234r"
    url: "jdbc:mysql://localhost:3306/rapid-food_payments?createDatabaseIfNotExist=true"
  kafka:
    bootstrap-servers: "http://localhost:29092"
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082


kafka:
  topics:
    order-create: "order.created"
